### ISSUE TITLE
Merge into dokan-dev/dokan-java

### ISSUE THREAD

**Issue by ghost** [jhult/dokany-java#1]
Hi,

Great work.
Could you please merge this repo to https://github.com/dokan-dev/dokan-java.

Thanks

**Comment by Rondom** [comment]
Hi @jhult and @soywiz,
would you be interested in developing this inside the https://github.com/dokan-dev/dokan-java repository. I am sure @Liryna would give you access.

Currently people see the stalled effort in the dokan-java-repository inside the dokan-java-repository and move on, probably not seeing the very good progress you have made already.

**Comment by jhult** [comment]
Done.
