### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by ayberkcal** [jhult/dokany-java#2]
Hi,
Anyone can explain current implementation status of project? I would like to use wrapper but I could not be sure current status of project. 
Thank you

**Comment by jhult** [comment]
It is a work in progress. Feel free to contribute.

I recently re-started work using [JNR](https://github.com/jnr/jnr-ffi).

**Comment by ayberkcal** [comment]
Very happy to contribute! But first I need to understand exact status of implementations (which methods are implemented, which are not etc.). Do you have any checklist for or guide?
Also dipped into library and I did not see JNR references. You did not push to repo?
Thank you!

**Comment by jhult** [comment]
I pushed the [JNR branch](https://github.com/jhult/dokany-java/tree/jnr).

Both branches should compile. JNA is closer to working. JNR still has issues with figuring out how to call the DOKANY_OPERATIONS callbacks.
